#111 Add coroutine dispatcher qualifier
Android-Guild/Picover pull request #206
Opened 2023-09-14 13:27 UTC by MarekMacko

2023-09-14 19:16 UTC, michal-kucznerowicz requested changes

2023-09-14 19:16 UTC, michal-kucznerowicz commented on app/src/main/kotlin/com/intive/picover/common/coroutines/dispatcher/Dispatcher.kt
> +	@Retention(AnnotationRetention.BINARY)
Why do we need to retain this annotation in binary output?

2023-09-14 19:16 UTC, michal-kucznerowicz commented on app/src/main/kotlin/com/intive/picover/common/coroutines/dispatcher/Dispatcher.kt
> +	annotation class IO
You can also specify annotation target e.g. `@Target(AnnotationTarget.PROPERTY, AnnotationTarget.VALUE_PARAMETER, AnnotationTarget.FUNCTION)`

2023-09-15 08:00 UTC, MarekMacko commented on app/src/main/kotlin/com/intive/picover/common/coroutines/dispatcher/Dispatcher.kt
> +	@Retention(AnnotationRetention.BINARY)
That's the review I was looking for 😄 Good point, I'll change it to `SOURCE`

2023-09-15 08:01 UTC, MarekMacko commented on app/src/main/kotlin/com/intive/picover/common/coroutines/dispatcher/Dispatcher.kt
> +	annotation class IO
I'll set it only to `@Target(AnnotationTarget.FUNCTION, AnnotationTarget.VALUE_PARAMETER)`, `PROPERTY` is not needed at this moment.

2023-09-15 08:10 UTC, michal-kucznerowicz approved these changes

2023-09-15 08:21 UTC, marcinWisnia approved these changes

2023-09-15 08:30 UTC, merged