#215 Simplify version catalog
Android-Guild/Picover pull request #240
Opened 2023-09-19 11:38 UTC by MarekMacko

2023-09-19 20:52 UTC, michal-kucznerowicz requested changes

2023-09-19 20:52 UTC, michal-kucznerowicz commented on gradle/libs.versions.toml
> +android-compose-navigation = "androidx.navigation :navigation-compose:2.7.2"
Redundant spaces

2023-09-20 06:53 UTC, MarekMacko commented on gradle/libs.versions.toml
> +android-compose-navigation = "androidx.navigation :navigation-compose:2.7.2"
Done, thanks!

2023-09-20 07:09 UTC, marcinWisnia approved these changes

2023-09-20 07:11 UTC, michal-kucznerowicz approved these changes

2023-09-20 07:24 UTC, merged