#119 change party id type
Android-Guild/Picover pull request #404
Opened 2023-11-09 13:28 UTC by kmaslowiec

2023-11-09 13:59 UTC, MarekMacko requested changes

2023-11-09 13:59 UTC, MarekMacko commented on app/src/main/kotlin/com/intive/picover/parties/view/PartiesScreen.kt
>  			id = it,
Just use `it.toString()`

2023-11-10 10:09 UTC, MarekMacko commented on app/src/main/kotlin/com/intive/picover/parties/view/PartiesScreen.kt
> +	val parties = (1..5).map { it.toString() }
There is no need for two consecutive `map` operators, keep it simple and merge them into one

2023-11-10 11:01 UTC, kmaslowiec commented on app/src/main/kotlin/com/intive/picover/parties/view/PartiesScreen.kt
> +	val parties = (1..5).map { it.toString() }
Done

2023-11-10 11:43 UTC, MarekMacko commented on app/src/main/kotlin/com/intive/picover/parties/view/PartiesScreen.kt
> +	val parties = (1..5).map { it.toString() }
Fix CI errors and we're ready to go!

2023-11-10 11:59 UTC, kmaslowiec commented on app/src/main/kotlin/com/intive/picover/parties/view/PartiesScreen.kt
> +	val parties = (1..5).map { it.toString() }
Done

2023-11-10 12:07 UTC, MarekMacko approved these changes

2023-11-10 12:10 UTC, merged